{% set version = "0.1.1" %}

package:
  name: soapysdr-module-audio
  version: {{ version }}

source:
  url: https://github.com/pothosware/SoapyAudio/archive/soapy-audio-{{ version }}.tar.gz
  sha256: 856150d6ca472d3f53b7ac34eb4a218bdea44494012e23e0a592e454dc68d835
  patches:
    - 0001-SoapyAudio-hamlib-control-not-working-for-Softrock.patch
    - 0002-In-hamlib-4.2-the-FILPATHLEN-was-replaced-by-HAMLIB_.patch
    - 0003-Fix-catching-exception-by-copy.patch

build:
  number: 2
  ignore_run_exports_from:
    - winpthreads-devel  # [win]

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - pkg-config
  host:
    - hamlib
    - rtaudio <6
    - soapysdr
    # needed just for a header to compile against hamlib, but not linked against
    - winpthreads-devel  # [win]

test:
  commands:
    # verify that libraries get installed
    - test -f $PREFIX/lib/SoapySDR/modules{{ soapysdr }}/libaudioSupport.so  # [not win]
    - if not exist %PREFIX%\\Library\\lib\\SoapySDR\\modules{{ soapysdr }}\\audioSupport.dll exit 1  # [win]

    # show info to see if module is detected
    - SoapySDRUtil --info
    - SoapySDRUtil --info | grep audioSupport  # [not win]
    - SoapySDRUtil --info | findstr /l audioSupport  # [win]

about:
  home: https://github.com/pothosware/SoapyAudio/wiki
  license: MIT
  license_file: LICENSE.txt
  summary: 'SoapySDR plugin for audio devices'
  description: >
    The Soapy Audio project provides a plugin module for sound card devices
    within the SoapySDR API and for software that supports SoapySDR. In
    addition, SoapyAudio includes optional support for hamlib, which provides
    basic gain and frequency controls for certain tuners which may be paired
    with an audio device.
  doc_url: https://github.com/pothosware/SoapyAudio/wiki
  dev_url: https://github.com/pothosware/SoapyAudio

extra:
  recipe-maintainers:
    - ryanvolz
